[package]
name = "opus"
version = "0.1.0"
edition = "2024"
authors = ["NullSector-dev"]
license = "MIT" 

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = "0.29.0"
serde = { version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
